### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by ZexMaxwell001** [Maselkov/GW2Bot-Red#11]
So, from time to time, I'm getting this error. what can I do to help report the issue?

![image](https://user-images.githubusercontent.com/1289187/28291105-b3482c70-6b0e-11e7-9733-3f83c25bbc53.png)

**Comment by Maselkov** [comment]
This is due to a mistake in yesterday's maintenance. It's fixed now. API is down as well, so let's hope nobody noticed :P
