### ISSUE TITLE
Bot doesn't respond in channels.

### ISSUE THREAD

**Issue by harry2258** [Maselkov/GW2Bot-Red#14]
This issue has been happening for quite some time and I've ran out of ideas to try.

- The permissions are set properly I believe (http://i.imgur.com/GZl6sRM.png)
- I've also tried to give it admin to see if that would fix it, It didn't not.
- I've also invited it to another server and it responds in that channel.

I'm not sure if I've messed up the permission somehow but troubleshooting idea would be great.

Thanks again for this awesome bot!

**Comment by Maselkov** [comment]
First try reinviting the bot - that fixed the problem for some server, apparently.

Otherwise contact me by joining the [support server](https://discord.gg/VyQTrwP) or at Maselkov#2365

**Comment by Maselkov** [comment]
Solved, was a prefix issue
