### ISSUE TITLE
Add a wiki link to the skill title in skillinfo

### ISSUE THREAD

**Issue by godfat** [Maselkov/GW2Bot-Red#16]
What do you think? It would be useful to have a link in the skill title.

Maybe somewhere around https://github.com/Maselkov/GW2Bot/blob/develop/cogs/guildwars2.py#L1920

I never wrote a discord bot before, so I am unsure if this is doable. I could try to make the change but I don't know how to test it.

We just need to convert the spaces into underscores:

``` python
def name2wiki(name):
  return "https://wiki.guildwars2.com/wiki/" + name.replace(' ', '_')
```

**Comment by Maselkov** [comment]
Do all skills have a wiki page with such name format?

**Comment by godfat** [comment]
I can't say it's 100% because I can't check all the skills, but as far as I could tell, yes.

https://wiki.guildwars2.com/wiki/Well_of_Eternity

This is also the case in GW1 which I wrote a skill template exporter. I believe it's the case for at least 95%.

I think it's fine even if it leads to 404. We could see why they're not the case then.

**Comment by Maselkov** [comment]
I'm thinking, you could do a HEAD request to see if it returns 404

**Comment by godfat** [comment]
I won't bother because that's adding extra latency. The server could even be down and the link could still be legit. Even if the entry doesn't exist yet, people could create the wiki entry in the future. (e.g. PoF skills, perhaps)

On the other hand, you're already doing asynchronous stuff, and editing the message. Perhaps we could also edit the message and remove the link when we realized that there's no such page. However this might not work well in the case that the wiki server is down, or broken in some way. I don't feel this is worth the effort, but you could try.

**Comment by Maselkov** [comment]
Latency would be minimal though, especially considering since currently skillinfo is near instantaneous. Anyway this should be trivial to implement, I'll test soon

**Comment by godfat** [comment]
Cool, thanks for trying to add it! It would be very useful.

**Comment by Maselkov** [comment]
Deployed, thank you for suggestion

**Comment by godfat** [comment]
Awesome, just tested, works like a charm.
