### ISSUE TITLE
Daily command from another Discord bot

### ISSUE THREAD

**Issue by XilverGG** [Maselkov/GW2Bot-Red#8]
I'm trying to create a bot to send daily messages like $daily fractals for example but the GW2 Bot doesen't read the commands from my bot.

Do you know why it can be?

**Comment by Maselkov** [comment]
The bot ignores messages from other bots, fully intended. This is to prevent loops and abuse.

There's `$daily notifier` if you want the bot to post dailies every day at reset time.
